name = input ("Enter your name: ")
place = input("Enter the place u went: ")
verb = input("Enter the verb: ")
thing = input("Enter the thing u buy: ")
print("\nStory: ")
print(f"One day {name} went to {place} with his friends.")
print(f"In {place} {name } sees many things.")
print(f"{name} {verb} with his friends in {place}.")
print(f"{name} buy {thing} for his family.")